### ISSUE TITLE
Update GNOME Twitch to 0.1.0

### ISSUE THREAD

**Issue by vinszent** [ckorn/GetDeb#10]
I've tagged and released 0.1.0 now could you please update the corresponding [GetDeb package](http://www.getdeb.net/app/GNOME%20Twitch).

You can use the v0.1.0-autotools release. Also please note that clutter-gst-3.0 and clutter-gtk-1.0 are now dependencies.

I will now hopefully be tagging releases on a regular basis.

**Comment by ckorn** [comment]
But there is only clutter-gst 2.0 [1] and clutter-gtk 1.0 [2] in Ubuntu 15.04. Will it work anyway?

[1] http://packages.ubuntu.com/vivid/libclutter-gst-2.0-dev
[2] http://packages.ubuntu.com/vivid/libclutter-gtk-1.0-dev

**Comment by vinszent** [comment]
No unfortunately not, as the entire ClutterGstPlayback (which is what I use to play the streams) was introduced in clutter-gst-3.0. Seems like 3.0 is available in [Wily](http://packages.ubuntu.com/wily/libclutter-gst-3.0-0) at least but unless Canonical backports 3.0 to 15.04 then I guess Wily will have to be the minimum version.

I'm not too fond of keeping the old version of it up, but you can decide whether to remove it or not. However when 15.10 Wily is released (In ~3 days, October 22nd I think?) I would really appreciate it if you released a package for it then. Thank you for your efforts!
