### ISSUE TITLE
getdeb-repository package

### ISSUE THREAD

**Issue by darealshinji** [ckorn/GetDeb#3]
I made some updates to the getdeb-repository and playdeb packages. It's mostly changes in the installation scripts. I've added a preinst script, removed sudo commands and made postinst compatible to Linux Mint.
Please take a look and tell me what you think:
https://github.com/darealshinji/GetDeb/tree/getdeb-repository
https://github.com/darealshinji/PlayDeb/tree/playdeb-repository

I had to create the initial commit from the binary packages since I couldn't find any source packages, despite the GPL license.

**Comment by ckorn** [comment]
Linux Mint is not supported officially. But they ship with our repositories anway. You just have to enable them I think.

**Comment by darealshinji** [comment]
The main goal wasn't actually the Mint compatibility, it was the fixes in the scripts and to publish the source code, which GPL requires.
